[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "eppo_metrics_sync"
dynamic = ["version"]
description = "Sync metrics to Eppo"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "PyYAML",
    "jsonschema",
    "requests",
]

[tool.setuptools_scm]
version_file = "eppo_metrics_sync/_version.py"

[tool.setuptools]
packages = ["eppo_metrics_sync"]

[tool.setuptools.package-data]
eppo_metrics_sync = ["schema/*"]
