name: Run Pytest

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_functionality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pytest tests

  test_installation:
    runs-on: ubuntu-latest
    needs: test_functionality

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Installation Test
        run: |
          pytest tests/test_integration.py::test_package_installation_and_dependencies -v
